services:
  db:
    image: mysql:latest
    restart: always
    container_name: myphpapp-db
    environment:
      MYSQL_ROOT_PASSWORD: somepass
      MYSQL_DATABASE: somedatabase
    volumes:
      - my-vol:/var/lib/mysql
  dbclient:
    image: mysql:latest
    depends_on:
      - db
    command: mysql -uroot -psomepass -hdb

volumes:
  my-vol:
    name: my-vol
